name: CI
on:
  push:
    branches: [ main ]
    workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
- name: Setup Node.js
  uses: actions/setup-node@v3.5.1
  with:
    node-version: 16:13:2
